include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    argument_type_not_assignable: true
    prefer_interpolation_to_compose_strings: true
    invalid_assignment: true
    return_of_invalid_type_from_closure: true
    unnecessary_cast: true
    unnecessary_const: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    sized_box_for_whitespace: true
    unused_field: false
    constant_identifier_names: false
    annotate_overrides: false
    avoid_function_literals_in_foreach_calls: false
    library_private_types_in_public_api: false

analyzer:
  exclude:
  errors:
    missing_required_param: error
